[workspace]

members = [
    "ccwc", 
    "cut", 
    "http-load-tester", 
    "huffman-compression", 
    "json-parser", 
    "load-balancer", 
    "redis-server", 
    "sort-tool", 
    "web-server",
]

resolver = "2"
